name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@master
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v1
    - name: Set qshell 2.6.2
      uses: foxundermoon/setup-qshell@master
      with:
        qshell-version: '2.6.2'

    - name: test qshell
      run: qshell version
